# ESPHome configuration for the MS430.

# Copyright 2025 Metriful Ltd.
# Licensed under the MIT License - for further details see LICENSE.txt

# For code examples, datasheet and user guide, visit
# https://github.com/metriful/sensor

# This file must be included in another yaml configuration file, in
# which "particle_sensor_disabled" and "temperature_offset" are defined
# as substitutions.

#########################################################################

external_components:
  - source:
      type: local
      path: esphome_components

sensor:
  - platform: ms430
    temperature:
      name: "Temperature"
      icon: "mdi:thermometer"
      filters:
      - offset: ${temperature_offset}
    humidity:
      name: "Humidity"
      icon: "mdi:cloud-percent"
    pressure:
      name: "Air pressure"
      icon: "mdi:weather-partly-rainy"
    gas_resistance:
      name: "Gas sensor resistance"
      icon: "mdi:scent"
    white_light:
      name: "White light level"
      icon: "mdi:circle-outline"
    illuminance:
      name: "Illuminance"
      icon: "mdi:white-balance-sunny"
    particle_duty:
      name: "Particle sensor duty cycle"
      icon: "mdi:square-wave"
      internal: ${particle_sensor_disabled}
    particle_concentration:
      name: "Particle concentration"
      icon: "mdi:chart-bubble"
      internal: ${particle_sensor_disabled}
    aqi:
      name: "Air quality index"
      icon: "mdi:flower-tulip-outline"
      on_value_range:
        - above: -0.5
          below: 50
          then:
            - text_sensor.template.publish:
                id: aqi_text
                state: "Good"
        - above: 50
          below: 100
          then:
            - text_sensor.template.publish:
                id: aqi_text
                state: "Acceptable"
        - above: 100
          below: 150
          then:
            - text_sensor.template.publish:
                id: aqi_text
                state: "Substandard"
        - above: 150
          below: 200
          then:
            - text_sensor.template.publish:
                id: aqi_text
                state: "Poor"
        - above: 200
          below: 300
          then:
            - text_sensor.template.publish:
                id: aqi_text
                state: "Bad"
        - above: 300
          then:
            - text_sensor.template.publish:
                id: aqi_text
                state: "Very bad"
    e_co2:
      name: "Estimated CO₂"
      icon: "mdi:molecule-co2"
    b_voc:
      name: "Equivalent breath VOC"
      icon: "mdi:account-voice"
    iaq_accuracy:
      name: "Air quality accuracy"
      internal: true
      on_value_range:
        - above: -0.5
          below: 0.5
          then:
            - text_sensor.template.publish:
                id: aqi_acc_text
                state: "Not yet valid"
        - above: 0.5
          below: 1.5
          then:
            - text_sensor.template.publish:
                id: aqi_acc_text
                state: "Low"
        - above: 1.5
          below: 2.5
          then:
            - text_sensor.template.publish:
                id: aqi_acc_text
                state: "Medium"
        - above: 2.5
          then:
            - text_sensor.template.publish:
                id: aqi_acc_text
                state: "High"
    sound_spl:
      name: "Sound pressure level"
      icon: "mdi:microphone"
    sound_peak:
      name: "Peak sound amplitude"
      icon: "mdi:waveform"
    sound_band_0:
      name: "SPL at 125 Hz"
      icon: "mdi:sine-wave"
    sound_band_1:
      name: "SPL at 250 Hz"
      icon: "mdi:sine-wave"
    sound_band_2:
      name: "SPL at 500 Hz"
      icon: "mdi:sine-wave"
    sound_band_3:
      name: "SPL at 1000 Hz"
      icon: "mdi:sine-wave"
    sound_band_4:
      name: "SPL at 2000 Hz"
      icon: "mdi:sine-wave"
    sound_band_5:
      name: "SPL at 4000 Hz"
      icon: "mdi:sine-wave"


text_sensor:
  - platform: template
    name: "Air quality accuracy"
    icon: "mdi:magnify"
    id: aqi_acc_text
  - platform: template
    name: "Air quality"
    icon: "mdi:flower-tulip-outline"
    id: aqi_text
